on:
  push:
  workflow_dispatch:

env:
  IMAGE: ghcr.io/${{ github.repository }}

jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        client: [ 'podman', 'docker' ]
    steps:
      - uses: actions/checkout@v2

      - name: Create a Dockerfile
        run: |
          echo 'FROM alpine' > Dockerfile
          echo 'LABEL org.opencontainers.image.description "An image created by ${{ matrix.client }}"' >> Dockerfile
          echo 'ENTRYPOINT ["echo", "Hello from ${{ github.repository }}!"]' >> Dockerfile

      - name: Build image
        run: ${{ matrix.client }} build . -t ${IMAGE,,}:${{ matrix.client }} # lowercase IMAGE

      - name: Login to ghcr.io
        run: ${{ matrix.client }} login ghcr.io -u token --password-stdin <<< ${{ secrets.GITHUB_TOKEN }}

      - name: Publish image
        run: ${{ matrix.client }} push ${IMAGE,,}:${{ matrix.client }} # lowercase IMAGE

      - name: Inspect image
        run: ${{ matrix.client }} image inspect ${IMAGE,,}:${{ matrix.client }} # lowercase IMAGE
